# databases:
#   - name: mmefu_ego_app
#     databaseName: mmefu_ego_app
#     user: mmefu_ego_app

# services:
#   - type: web
#     name: mmefu_ego_app
#     env: ruby
#     buildCommand: "./bin/render-build.sh"
#     startCommand: "bundle exec puma -C config/puma.rb"
#     envVars:
#       - key: DATABASE_URL
#         fromDatabase:
#           name: mmefu_ego_app
#           property: connectionString
#       - key: RAILS_MASTER_KEY
#         sync: false

databases:
  - name: mmefu_ego_app
    databaseName: mmefu_ego_app
    user: mmefu_ego_app

services:
  - type: web
    env: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mmefu_ego_app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
        plan: free
